apiVersion: v2
name: tperf
description: Runs comparative performance test with and without Teleport
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: tbot
    version: "^18.7.6"
    repository: "https://charts.releases.teleport.dev"