---
### Required Configuration Items
# Copy these to your values file and fill them in

group: "" # k8s group name for RoleBinding, should match Teleport Role
teleport_proxy_ip: "" # Optional IP to use as a hostAlias for the Teleport proxy in the runner pod

# See https://github.com/gravitational/teleport/tree/master/examples/chart/tbot
tbot:
  # Configure these when you deploy this chart
  clusterName: "" # Teleport FQDN
  teleportProxyAddress: "" # Teleport FQDN:443
  token: "" # Name of Teleport token object for tbot join
  services:
  - type: kubernetes/v2
    selectors:
    - name: "" # Name k8s cluster used when joining Teleport
    destination:
      type: kubernetes_secret
      name: "" # Name tbot uses for secret -- make this unique to this job
      namespace: "" # Namespace for secret

### Test Configuration
# Copy the ones you want to modify to your values file

app_name: "tperf"

# Number of tests run by each job
iterations: 1
# Test type: 'exec' runs command in the target pod, 'ls' runs `kubectl get pods`
type: "exec"
# The number of tests that should be run. Probably in parallel, but depends on
# how k8s schedules them.
# TODO: Impmement barrier to ensure they run in parallel
replicas: 1

# Use `dd of=/dev/zero bs=# count=#` to send lots of data / test throughput 
command: "echo hello" # quick, tests latency

# Input to command via `dd`. Only matters of the command above reads data.
input:
  count: 0
  block_size: 0
  # Use /dev/urandom to uncompressable data Teleport doesn't do compression, but 
  # your can verify nothing in the stack does. Since it's encrypted, compression
  # should't be possible/effective a lower levels of the stack.
  file: "/dev/zero"

# How long to wait for the target pod to become ready
max_wait: "5m"
# How many times to retry failed jobs
backoff_limit: 3

debug_runner_pod: false

##############################################################################
