---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tperf.target-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tperf.target-labels" . | nindent 4 }}
spec:
  serviceName: target
  replicas: {{ .Values.replicas }} 
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      {{- include "tperf.target-labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tperf.target-labels" . | nindent 8 }}
    spec:
      containers:
      - name: target
        image: busybox:latest
        command:
        - /bin/sh
        - -c
        - |
          trap 'exit 0' TERM INT
          while true; do
            sleep 10 &
            wait $!
            echo 'TODO: Run tests'
          done
        volumeMounts:
        - name: results
          mountPath: {{ include "tperf.results-dir" . }}
          readOnly: false
      volumes:
      - name: results
        emptyDir: {}