---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tperf.test-runner-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "tperf.test-runner-name" . }}
spec:
  serviceName: test-runner
  replicas: {{ .Values.replicas }}
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: {{ include "tperf.test-runner-name" . }}
  template:
    metadata:
      labels:
        app: {{ include "tperf.test-runner-name" . }}
    spec:
      serviceAccountName: {{ include "tperf.sa-name" . }}
      initContainers:
      - name: copy-kubectl
        image: bitnami/kubectl:latest
        command:
        - sh
        - -ec
        - |
          cp "$(command -v kubectl)" /opt/bin/
          chmod +x /opt/bin/kubectl
        volumeMounts:
        - name: bin
          mountPath: /opt/bin
      containers:
      - name: test-runner
        image: "{{ .Values.tsh.repository }}:{{ .Values.tsh.tag }}"
        command: ["/busybox/sh", "-c", "while true; do sleep 30; echo 'TODO: Run tests'; done"]
        env:
        - name: PATH
          value: /opt/scripts:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/busybox
        - name: TELEPORT_PROXY
          value: {{ .Values.tbot.teleportProxyAddress }}
        # See: https://goteleport.com/docs/reference/machine-workload-identity/configuration/#identitykey-agent
        - name: TELEPORT_KEY_AGENT_DIR
          value: /opt/machine-id
        - name: TELEPORT_IDENTITY_FILE
          value: /opt/machine-id/identity
        volumeMounts:
        - name: bin
          mountPath: /opt/bin
          readOnly: true
        - name: tbot
          mountPath: /opt/machine-id
          readOnly: true
        - name: scripts
          mountPath: /opt/scripts
          readOnly: true
      volumes:
      # binaries we copy from other containers
      - name: bin
        emptyDir: {}
      # tbot-managed credentials
      - name: tbot
        secret:
          secretName: {{ required "Please let tbot_secret to the name of a kubernetes service with a kubernetes_secret destination configured in tbot.services or tbot.outputs values for this chart" .Values.tbot_secret }}
      # Static scripts
      - name: scripts
        configMap:
          name: {{ include "tperf.scripts" . }}
          defaultMode: 0755