---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "tperf.test-runner-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tperf.runner-labels" . | nindent 4 }}
spec:
  completionMode: Indexed
  parallelism: {{ .Values.replicas }}
  completions: {{ .Values.replicas }}
  backoffLimit: {{ .Values.backoff_limit }}
  template:
    metadata:
      labels:
        {{- include "tperf.runner-labels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "tperf.sa-name" . }}
      containers:
      - name: test-runner
        image: bitnami/kubectl:latest
        command:
        - race-kubectl
        env:
        - name: ORDINAL
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
        - name: CMD
          value: {{ .Values.command | quote }}
        - name: TYPE
          value: {{ .Values.type | quote }}
        - name: ITERATIONS
          value: {{ .Values.iterations | quote }}
        - name: TX_COUNT
          value: {{ .Values.input.count | quote }}
        - name: TX_BLOCK_SIZE
          value: {{ .Values.input.block_size | quote }}
        - name: TX_INFILE
          value: {{ .Values.input.file | quote }}
        - name: MAX_READY_WAIT
          value: {{ .Values.max_wait | quote }}
        - name: PATH
          value: /opt/bin:/opt/bitnami/common/bin:/opt/bitnami/kubectl/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin # kubectl
        - name: TELEPORT_PROXY
          value: {{ .Values.tbot.teleportProxyAddress | quote }}
        - name: TARGET_PREFIX
          value: {{ include "tperf.target-name" . }}
        - name: OUT
          value: {{ printf "%s/results.tsv" (include "tperf.results-dir" .) }}
        {{- if .Values.debug_runner_pod }}
        - name: DEBUG
          value: "true"
        {{- end }}
        volumeMounts:
        - name: tbot
          mountPath: /opt/machine-id
          readOnly: true
        - name: scripts
          mountPath: /opt/bin
          readOnly: true
        - name: results
          mountPath: {{ include "tperf.results-dir" . }}
          readOnly: false
      volumes:
      # tbot-managed credentials
      - name: tbot
        secret:
          secretName: {{ required "Please set tbot.services[0].destination.name to the name of a kubernetes service with a kubernetes_secret destination configured in tbot.services or tbot.outputs values for this chart" (index .Values.tbot.services 0).destination.name }}
      # Static scripts
      - name: scripts
        configMap:
          name: {{ include "tperf.scripts" . }}
          defaultMode: 0755
      - name: results
        emptyDir: {}
