---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tperf.test-runner-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "tperf.test-runner-name" . }}
spec:
  serviceName: test-runner
  replicas: {{ .Values.replicas }}
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: {{ include "tperf.test-runner-name" . }}
  template:
    metadata:
      labels:
        app: {{ include "tperf.test-runner-name" . }}
      annotations:
        # So configmap changes make this sts reload
        checksum/scripts: {{ (.Files.Glob "files/*").AsConfig | sha256sum | quote }}
    spec:
      serviceAccountName: {{ include "tperf.sa-name" . }}
      containers:
      - name: test-runner
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          trap 'exit 0' TERM INT
          while true; do
            sleep 10 &
            wait $!
            echo 'TODO: Run tests'
          done
        env:
        - name: PATH
          value: /opt/bin:/opt/bitnami/common/bin:/opt/bitnami/kubectl/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin # kubectl
        - name: TELEPORT_PROXY
          value: {{ .Values.tbot.teleportProxyAddress }}
        - name: TARGET_PREFIX
          value: {{ include "tperf.target-name" . }}
        volumeMounts:
        - name: tbot
          mountPath: /opt/machine-id
          readOnly: true
        - name: scripts
          mountPath: /opt/bin
          readOnly: true
      volumes:
      # tbot-managed credentials
      - name: tbot
        secret:
          secretName: {{ required "Please let tbot_secret to the name of a kubernetes service with a kubernetes_secret destination configured in tbot.services or tbot.outputs values for this chart" .Values.tbot_secret }}
      # Static scripts
      - name: scripts
        configMap:
          name: {{ include "tperf.scripts" . }}
          defaultMode: 0755