#!/usr/bin/env bash
set -euo pipefail

declare -r DEBUG="${DEBUG:-}"
debug() {
  [[ -n "${DEBUG}" && "$(echo "${DEBUG}" | tr 'a-z' 'A-Z')" != "FALSE" ]]
}
on_fail() {
  ret="$?"
  printf >&2 "race-kubectl failed with exit %s\n" "${ret}"
  while true; do
    sleep 10 &
    wait $!
    echo 'Waiting for you to debugtest-runner'
  done
}
if debug; then
  set -Ex
  trap on_fail ERR
fi

# Mark start in the logs
date >&2

msg() {
  printf >&2 "%s\n" "${*}"
}

die() {
  msg "ERROR: ${*}"
  debug && on_fail
  exit 1
}

declare -r ITERATIONS="${ITERATIONS:-1}"
declare -r TYPE="${TYPE:-exec}" # TODO: add port-forward and watch test types
declare -r CMD="${CMD:-}"
declare -r OUT="${OUT:-/dev/shm/output.tsv}"
declare -r OUT_TARGET_TEMPLATE="${OUT_TARGET_TEMPLATE:-${OUT}.#}"
declare -r TX_COUNT="${TX_COUNT:-0}"
declare -r TX_BLOCK_SIZE="${TX_BLOCK_SIZE:-0}"
declare -r TX_INFILE="${TX_INFILE:-/dev/zero}"
declare -r MAX_READY_WAIT="${MAX_READY_WAIT:-5m}"

declare -r TELEPORT_KUBECONFIG="${TELEPORT_KUBECONFIG:-/opt/machine-id/kubeconfig.yaml}"

case "${TYPE}" in 
  exec)
    [[ -n "${CMD}" ]] || die "CMD must NOT be empty when TYPE == 'exec', got '${CMD}'"
    ;;
  ls)
    [[ -z "${CMD}" ]] || die "CMD must be empty when TYPE == 'ls', got '${CMD}'"
    ;;
  *)
    # TODO: implement other types here
    ;;
esac

[[ -r "${TELEPORT_KUBECONFIG}" ]] \
  || die "Teleport kubeconfig '${TELEPORT_KUBECONFIG}' isn't readable or doesn't exist"

declare -r ORDINAL="${ORDINAL:-NOT_SET}"
[[ "${ORDINAL}" =~ ^[0-9][0-9]*$ ]] \
  || die "ORDINAL '${ORDINAL}' not set or not a number. ORDINAL must be set to match the index of a target pod. This should be done by using in Indexed Job and setting it to the annotation 'batch.kubernetes.io/job-completion-index'"

declare -r OUT_TARGET="${OUT_TARGET_TEMPLATE//\#/$ORDINAL}"

declare -r TARGET_PREFIX="${TARGET_PREFIX:-}"
[[ -n "${TARGET_PREFIX}" ]] \
  || die "TARGET_PREFIX not set. Set it to the name of the remote StatefulSet we're running on."
declare -r TARGET_POD="${TARGET_PREFIX}-${ORDINAL}"

wait_for_pod() {
  local pod="${1}"
  local max="${2:-5000}"
  [[ -z "${pod}" ]] && {
    echo >&2 "Pod empty in wait_for_pod"
    exit 1;
  }
  until (set -x; kubectl get "pod/${pod}") || [[ "${max}" -le 0 ]]; do
    printf >&2 "Waiting for target pod '%s' to exist...%d\n" "${pod}" "${max}"
    sleep 1
    max="$(( max - 1 ))"
  done
}
export -f wait_for_pod # Because timeout won't work with functions
# We use if+case because we've set -e -- timeout failure would cause exit
if timeout "${MAX_READY_WAIT}" bash -c "wait_for_pod '${TARGET_POD}'"; then
  msg "Pod '${TARGET_POD}' exists, waiting for it to be ready..."
else
  ret="${?}"
  case "${ret}" in
    124) die "Timed out waiting for pod '${TARGET_POD}' to exist" ;;
    0) die "This should be unreachable code" ;;
    *) die "Unknown failure waiting for target pod '${TARGET_POD}' to exist." ;;
  esac
fi

declare -r OUT_POD_NO_TP="${OUT_POD_NO_TP:-/dev/shm/${TARGET_POD}.no-teleport.yaml}"
kubectl get "pod/${TARGET_POD}" -o yaml \
  > "${OUT_POD_NO_TP}" \
  || die "Failed to query target pod '${TARGET_POD}' without Teleport"
declare -r OUT_POD_TP="${OUT_POD_TP:-/dev/shm/${TARGET_POD}.teleport.yaml}"
kubectl --kubeconfig="${TELEPORT_KUBECONFIG}" get "pod/${TARGET_POD}" -o yaml \
  > "${OUT_POD_TP}" \
  || die "Failed to query target pod '${TARGET_POD}' with Teleport"

diff "${OUT_POD_NO_TP}" "${OUT_POD_TP}" \
  || die "Target pod '${TARGET_POD}' differ when queried with and without Teleport. Are you sure your contexts are configured to access the same k8s cluster?"

run_test() {
  local CONFIG_FLAG="${1:-}"
  local before="$(date +%s%N)"
  local read_cmd='printf ""'
  local remote_cmd=(sh -c "${CMD} && cat >/dev/null")
  local kubectl_args=(exec -i "${TARGET_POD}" -- "${remote_cmd[@]}")

  if [[ "${TYPE}" == "ls" ]]; then
    kubectl_args=(get pods)
  fi

  [[ "${TYPE}" == "exec" && "${TX_BLOCK_SIZE}" -gt 0 ]] \
    && read_cmd="dd if=${TX_INFILE} bs=${TX_BLOCK_SIZE} count=${TX_COUNT}"
  
  (
    set -x;
    set +eo pipefail
    ${read_cmd} \
      | kubectl >&2 ${CONFIG_FLAG} "${kubectl_args[@]}" \
      | cat >/dev/null
  )
  local ret="${?}"
  local after="$(date +%s%N)"
  printf "%d\t%d\t%d\n" "${before}" "${after}" "${ret}"
}

kubectl wait \
  "pod/${TARGET_POD}" \
  --for=condition=ready \
  --timeout="${MAX_READY_WAIT}" \
  || die "Target pod '${TARGET_POD}' was not ready after '${MAX_READY_WAIT}'"
msg "Seeing permission errors about 'wait' above? Add perms, but things are still working. kubectl falls back to polling if it doesn't have wait perms."

sleep 1 # Because sometimes it takes a sec even after the pod is "ready"

printf "#%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n" \
  "task" \
  iter \
  "start_no_tp" \
  "end_no_tp" \
  "exit_code_no_tp" \
  "start_tp" \
  "end_tp" \
  "exit_code_tp" \
  | tee "${OUT}" \
  || die "Failed to print header"
for i in $(seq 1 "${ITERATIONS}"); do

  # Run without Teleport
  x_results="$(run_test)" \
    || die "Failed to run iteration '${i}' without Teleport"
  IFS=$'\t' read -r x_start x_end x_ret <<< "${x_results}"
  
  # Run with Teleport
  t_results="$(run_test "--kubeconfig=${TELEPORT_KUBECONFIG}")" \
    || die "Failed to run iteration '${i}' with Teleport"
  IFS=$'\t' read -r t_start t_end t_ret <<< "${t_results}"

  # Append results to putput file
  printf "%d\t%d\t%d\t%d\t%d\t%d\t%d\t%d\n" \
    "${ORDINAL}" "${i}" \
    "${x_start}" "${x_end}" "${x_ret}" \
    "${t_start}" "${t_end}" "${t_ret}" \
   | tee -a "${OUT}" \
   || die "Failed to print iteration '${i}'"
done

msg "Benchmark run complete, output at '${OUT}'"

if [[ -n "${OUT_TARGET}" ]]; then
  msg "Copying output to target"
  (set -x; kubectl cp "${OUT}" "${TARGET_POD}:${OUT_TARGET}")
else
  msg "OUT_TARGET_TEMPLATE not set, not copying to target pod"
fi

# Mark complete on the logs
date >&2
